//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_PDB.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public Nullable<int> CustomerOrderNumber { get; set; }
        public Nullable<int> AssignedEmployee { get; set; }
        public string OrderAmount { get; set; }
        public string AccountNumber { get; set; }
        public string TransactionDate { get; set; }
        public Nullable<bool> IsVIPOrder { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
